### ISSUE TITLE
Build workflow not inferring version number correctly

### ISSUE THREAD

**Issue by matt-graham** [astro-informatics/s2fft#283]
Within the build workflow the `cibuildwheel` jobs are not correctly inferring the version number using `setuptools_scm` from the Git tags due to 
https://github.com/actions/checkout/issues/1471 which means that the tags are not being checked out by the `actions/checkout` step. See for example [this run](https://github.com/astro-informatics/s2fft/actions/runs/13996983287/job/39194483107). 

We need to update the checkout Action configuration to explicitly request tags:

```YAML
- uses: actions/checkout@v4
  with:
    fetch-depth: 0
    fetch-tags: true
```
